"""empty message

Revision ID: 8bda0988692c
Revises: 9bae34c412aa
Create Date: 2018-05-19 12:00:27.969195

"""

# revision identifiers, used by Alembic.
revision = '8bda0988692c'
down_revision = '9bae34c412aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_payments', sa.Column('value', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_payments', 'value')
    # ### end Alembic commands ###
