"""empty message

Revision ID: 4d069ca9dcbd
Revises: 09f16dd361d5
Create Date: 2017-01-22 18:43:52.767831

"""

# revision identifiers, used by Alembic.
revision = '4d069ca9dcbd'
down_revision = '09f16dd361d5'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_debts', sa.Column('value', sa.Numeric(precision=7, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_debts', 'value')
    # ### end Alembic commands ###
