"""empty message

Revision ID: 63101372d7c6
Revises: dc8a3391c64a
Create Date: 2017-01-24 21:43:35.628744

"""

# revision identifiers, used by Alembic.
revision = '63101372d7c6'
down_revision = 'dc8a3391c64a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_debts', sa.Column('expiration_day', sa.Integer(), nullable=False))
    op.drop_column('users_debts', 'expiration_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_debts', sa.Column('expiration_date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('users_debts', 'expiration_day')
    # ### end Alembic commands ###
