"""empty message

Revision ID: dc8a3391c64a
Revises: 4d069ca9dcbd
Create Date: 2017-01-24 21:00:22.262644

"""

# revision identifiers, used by Alembic.
revision = 'dc8a3391c64a'
down_revision = '4d069ca9dcbd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_debts', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_debts', 'quantity')
    # ### end Alembic commands ###
